# Default Layout Configuration
# Standard 2x2 pane layout for Gas Town

name: default
description: "Standard 2x2 layout with Mayor and 3 Polecats"

panes:
  - name: mayor
    position: top-left
    size: 50%
    command: "gt mayor attach"
    
  - name: polecat-1
    position: top-right
    size: 50%
    command: "# Polecat 1 - Ready"
    
  - name: polecat-2
    position: bottom-left
    size: 50%
    command: "# Polecat 2 - Ready"
    
  - name: polecat-3
    position: bottom-right
    size: 50%
    command: "# Polecat 3 - Ready"

# Layout diagram:
# ┌──────────────┬──────────────┐
# │    Mayor     │  Polecat 1   │
# ├──────────────┼──────────────┤
# │  Polecat 2   │  Polecat 3   │
# └──────────────┴──────────────┘
